vich_uploader:
    db_driver: orm

    mappings:
        banners: # <--- вспоминаем значение, которое указывали в сущности и вписываем его здесь. Это идентификатор секции
            uri_prefix: /images/banners # <--- Префикс к пути наших картинок.
              # Например, с ним, наша картинка будет отображаться такому пути
            # http://localhost:8008/images/banners/custom-image.png
            upload_destination: '%kernel.project_dir%/public/images/banners' # <--- Сюда бандл будет загружать картинки.
            namer:
                service: vich_uploader.namer_hash # <--- Можно не менять. Сервис описывает способ именования картинкок. Обычный md5
                options: { algorithm: 'md5' }
